name: deploy to docker hub

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: container registries
        run: |
          docker login docker.io -u ${{ secrets.DOCKERUSERNAME }} -p ${{ secrets.DOCKERAPIKEY }}
      - name: build image
        run: | 
          repo="rjpadilla/mystery"
          tag1="original"
          tag2="tagged"
          docker build -t $repo:$tag1 .
          docker tag $repo:$tag1 $repo:$tag2
          docker push --all-tags docker.io/$repo
          # docker push docker.io/$repo:$tag1
          # docker push docker.io/$repo:$tag2